### ISSUE TITLE
pip install dask-cloudprovider

### ISSUE THREAD

**Issue by rpanai** [rsignell-usgs/sagemaker-fargate-test#3]
Hi Rich,
thank you for this repo. It looks like there are some problems installing

```
git+https://github.com/mrocklin/dask-cloudprovider.git@aiobotocore-1
```
Apparently the given branch doesn't exist anymore.

**Comment by rsignell-usgs** [comment]
Good catch!  Indeed that branch does not exist because the change was incorporated into the 0.2.0 release of dask-cloudprovider, now available on conda-forge!  I've modified the environment accordingly. 

Thanks so much for reporting this @rpanai and please report back more issues as you find them!
